version: '3.7'
services:
  mlem-bot:
    image: mlem-bot
    command: sh -c './wait-for mariadb:3306 -t 60000 -- node src/index.js'
    environment:
      - MLEM_BOT_TOKEN
      - MLEM_BOT_APPLICATION_ID
      - MLEM_BOT_GUILD_ID
    depends_on:
      - mariadb
    restart: always
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=foo
    restart: always